services:
  usermanagement:
    build: ./users
    container_name: usermanagement
    networks:
      - file-management-network
    ports:
      - 8081:8080    
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASSWORD}
      MySQL_DATABASE: ${MySQL_DATABASE}
      MySQL_USERNAME: ${MySQL_USERNAME}
      MySQL_PASSWORD: ${MySQL_PASSWORD}
      APIGATEWAY: 'api'
    
    volumes:
      - users:/home/app

  files:
    build: ./files
    container_name: filemanagement
    networks:
      - file-management-network
    ports:
      - 8082:8080
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASSWORD}
      MySQL_DATABASE: ${MySQL_DATABASE}
      MySQL_USERNAME: ${MySQL_USERNAME}
      MySQL_PASSWORD: ${MySQL_PASSWORD}
      APIGATEWAY: 'api'
    volumes:
      - files:/home/app
      - storage:/home/app/storage

  api:
    build: ./api
    container_name: apigateway
    networks:
      - file-management-network
    ports:
      - 8083:8080
    environment:
      USERSERVICE: usermanagement
      FILESERVICE: files
    volumes:
      - api:/home/app

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    environment:
      NEXT_PUBLIC_BACKEND_APP: api
      NEXT_PUBLIC_BACKEND_APP_PORT: 8083
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "1000"
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - file-management-network
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules/

networks:
  file-management-network:
    external: true

volumes:
  users:
  files:
  storage:
  api:
  frontend: