# mongod.conf
systemLog:
  verbosity: 0
  quiet: true
  component:
    accessControl:
      verbosity: 1
    storage:
      wt:
        wtCheckpoint:
          verbosity: 0

setParameter:
  enableDetailedConnectionHealthMetricLogLines: false