import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import ReduxProvider from "@/provider/ReduxProvider";
import ApiInitializer from "@/components/ApiInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased  bg-black`}
    >
      <body className="min-h-full flex flex-col bg-black">
        <ReduxProvider>
          <ApiInitializer />
          <Header></Header>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
