services:
  mysql:
    image: mysql:latest
    container_name: mysql-services
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MySQL_DATABASE}
      MYSQL_USER: ${MySQL_USERNAME}
      MYSQL_PASSWORD: ${MySQL_PASSWORD}
    networks:
      - file-management-network
    ports:
      - 3306:3306
    command: --init-file=/tmp/.init.sql
    volumes:
      - ./.init.sql:/tmp/.init.sql:ro
      - mysql_data:/var/lib/mysql
    restart: always

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASS}"]
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo:
    image: mongo
    container_name: mongodb_container
    restart: always
    command: ["mongod", "--quiet"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - file-management-network
    ports:
      - "27027:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      - file-management-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

networks:
  file-management-network:
    external: true

volumes:
  mysql_data:
  mongo_data: